// Generated by CoffeeScript 1.8.0
(function() {
  describe("the add method", function() {
    return it("will add numbers correctly", function() {
      return expect(Adder.add(2, 3)).toEqual(5);
    });
  });

}).call(this);
