// Generated by CoffeeScript 1.8.0
(function() {
  describe("Basket", function() {
    return it("should keep track of distict items and quantities in the basket", function() {
      var basket, laptop, mouse;
      basket = new Basket();
      laptop = new Item(1, "laptop", 400);
      mouse = new Item(2, "mouse", 10);
      basket.add(laptop);
      expect(basket.totalCount).toEqual(1);
      expect(basket.distinctCount).toEqual(1);
      basket.add(laptop);
      expect(basket.totalCount).toEqual(2);
      expect(basket.distinctCount).toEqual(1);
      basket.add(mouse);
      expect(basket.totalCount).toEqual(3);
      return expect(basket.distinctCount).toEqual(2);
    });
  });

}).call(this);
