// Generated by CoffeeScript 1.8.0
(function() {
  describe("Item", function() {
    var item;
    item = void 0;
    beforeEach(function() {
      return item = new Item(1, "Mouse", 10);
    });
    describe("updating an item", function() {
      return it("updates properties passed in", function() {
        item.update({
          title: "Super Mouse",
          price: 15
        });
        expect(item.title).toEqual("Super Mouse");
        expect(item.price).toEqual(15);
        return expect(item.id).toEqual(1);
      });
    });
    describe("Protected fields", function() {
      it("Should has the ID as protected field", function() {
        expect(item.protectedFields).toContain("id");
        return expect(item.protectedFields.length).toEqual(1);
      });
      it("Should let us add a protected field", function() {
        item.addProtectedField("title");
        return expect(item.protectedFields).toContain("title");
      });
      return it("should not allow an protected field to be updated", function() {
        item.addProtectedField("title");
        item.update({
          id: 2,
          title: "new title",
          price: 12
        });
        expect(item.id).toEqual(1);
        expect(item.title).toEqual("Mouse");
        return expect(item.price).toEqual(12);
      });
    });
    return describe("fieldIsProtected", function() {
      it("should return true if field is protected", function() {
        return expect(item.fieldIsProtected("id")).toBeTruthy();
      });
      return it("should return false, if field is not protected", function() {
        return expect(item.fieldIsProtected("title")).toBeFalsy();
      });
    });
  });

}).call(this);
