// Generated by CoffeeScript 1.8.0
(function() {
  var Basket;

  Basket = (function() {
    function Basket() {}

    Basket.prototype.items = [];

    Basket.prototype.ItemCount = 0;

    Basket.prototype.add = function(item) {
      this.items.push(item);
      return this.ItemCount++;
    };

    return Basket;

  })();

  window.Basket = Basket;

}).call(this);
