// Generated by CoffeeScript 1.8.0
(function() {
  var Item;

  Item = (function() {
    function Item(id, title, price) {
      this.id = id;
      this.title = title;
      this.price = price;
    }

    return Item;

  })();

  window.Item = Item;

}).call(this);
