// Generated by CoffeeScript 1.8.0
(function() {
  var Item;

  Item = (function() {
    function Item(id, title, price) {
      this.id = id;
      this.title = title;
      this.price = price;
    }

    Item.prototype.update = function(opts) {
      var key, value, _results;
      _results = [];
      for (key in opts) {
        value = opts[key];
        if (this[key] != null) {
          _results.push(this[key] = value);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Item;

  })();

  window.Item = Item;

}).call(this);
